# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.compute_Jk_rcpp <- function(v, s_k, p_k, Y, alpha, w, m, use0, use1, domain, select_domain, diss_d0_d1_L2, c_k, keep_k) {
    .Call(`_ProbKMA_package_compute_Jk_rcpp`, v, s_k, p_k, Y, alpha, w, m, use0, use1, domain, select_domain, diss_d0_d1_L2, c_k, keep_k)
}

.elongate_motifs <- function(V_new, V_dom, S_k, P_k, Y, w, m, use0, use1, alpha, c, c_max, max_elong, deltaJk_elong, trials_elong, D, K, max_gap, compute_motif, domain, select_domain, diss_d0_d1_L2) {
    invisible(.Call(`_ProbKMA_package_elongate_motifs`, V_new, V_dom, S_k, P_k, Y, w, m, use0, use1, alpha, c, c_max, max_elong, deltaJk_elong, trials_elong, D, K, max_gap, compute_motif, domain, select_domain, diss_d0_d1_L2))
}

.find_diss <- function(y, v, w, alpha, c_k, d, use0, use1, domain, select_domain, diss_d0_d1_L2) {
    .Call(`_ProbKMA_package_find_diss`, y, v, w, alpha, c_k, d, use0, use1, domain, select_domain, diss_d0_d1_L2)
}

.find_diss_aligned_rcpp <- function(y, v, w, alpha, aligned, d, use0, use1, domain, select_domain, diss_d0_d1_L2) {
    .Call(`_ProbKMA_package_find_diss_aligned_rcpp`, y, v, w, alpha, aligned, d, use0, use1, domain, select_domain, diss_d0_d1_L2)
}

.find_occurrences_cpp <- function(v, Y, R, alpha, w, c_k, use0, use1, diss_d0_d1_L2, domain, select_domain) {
    .Call(`_ProbKMA_package_find_occurrences_cpp`, v, Y, R, alpha, w, c_k, use0, use1, diss_d0_d1_L2, domain, select_domain)
}

.motifs_search_cpp <- function(Y, V, V0_clean, V1_clean, V_dom, V_length, P_clean, D_clean, V_hclust, alpha, use0, use1, w, c, max_gap, d, N, K, R_all, R_m, use_real_occurrences, length_diff, diss_d0_d1_L2, domain, select_domain) {
    .Call(`_ProbKMA_package_motifs_search_cpp`, Y, V, V0_clean, V1_clean, V_dom, V_length, P_clean, D_clean, V_hclust, alpha, use0, use1, w, c, max_gap, d, N, K, R_all, R_m, use_real_occurrences, length_diff, diss_d0_d1_L2, domain, select_domain)
}

.probKMA_silhouette_rcpp <- function(probKMA_results, domain, select_domain, diss_d0_d1_L2, align) {
    .Call(`_ProbKMA_package_probKMA_silhouette_rcpp`, probKMA_results, domain, select_domain, diss_d0_d1_L2, align)
}

