# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_Jk_rcpp <- function(v, s_k, p_k, Y, alpha, w, m, use0, use1, domain, select_domain, diss_d0_d1_L2, c_k = NULL, keep_k = NULL) {
    .Call(`_ProbKMA_package_compute_Jk_rcpp`, v, s_k, p_k, Y, alpha, w, m, use0, use1, domain, select_domain, diss_d0_d1_L2, c_k, keep_k)
}

elongate_motifs <- function(V_new, V_dom, S_k, P_k, Y, w, m, use0, use1, alpha, c, c_max, max_elong, deltaJk_elong, trials_elong, D, K, max_gap) {
    invisible(.Call(`_ProbKMA_package_elongate_motifs`, V_new, V_dom, S_k, P_k, Y, w, m, use0, use1, alpha, c, c_max, max_elong, deltaJk_elong, trials_elong, D, K, max_gap))
}

elongation_rcpp <- function(v_new_k, v_dom_k, s_k, p_k, len_elong_k, keep_k, c, domain, compute_motif, use0, use1, w, alpha, max_gap, Y, m, deltaJk_elong) {
    .Call(`_ProbKMA_package_elongation_rcpp`, v_new_k, v_dom_k, s_k, p_k, len_elong_k, keep_k, c, domain, compute_motif, use0, use1, w, alpha, max_gap, Y, m, deltaJk_elong)
}

find_diss <- function(y, v, w, alpha, c_k, d, use0, use1, domain, select_domain, diss_d0_d1_L2) {
    .Call(`_ProbKMA_package_find_diss`, y, v, w, alpha, c_k, d, use0, use1, domain, select_domain, diss_d0_d1_L2)
}

find_occurrences <- function(v, Y, R, alpha, w, c_k, use0, use1) {
    .Call(`_ProbKMA_package_find_occurrences`, v, Y, R, alpha, w, c_k, use0, use1)
}

select_motif <- function(D_clean, V_length, V_hclust, R_m, length_diff, n_hclust) {
    .Call(`_ProbKMA_package_select_motif`, D_clean, V_length, V_hclust, R_m, length_diff, n_hclust)
}

find_diss_aligned_rcpp <- function(y, v, w, alpha, aligned, d, use0, use1) {
    .Call(`_ProbKMA_package_find_diss_aligned_rcpp`, y, v, w, alpha, aligned, d, use0, use1)
}

probKMA_silhouette_rcpp <- function(probKMA_results, align) {
    .Call(`_ProbKMA_package_probKMA_silhouette_rcpp`, probKMA_results, align)
}

